export const ACTION_TYPES = {
  FETCH_CORONA_DATA: "FETCH_CORONA_DATA",
  FETCH_COUNTRY_DATA: "FETCH_COUNTRY_DATA",
  FETCH_SUMMARY_REPORT: "FETCH_SUMMARY_REPORT",
  FETCH_DETAILED_REPORT: "FETCH_DETAILED_REPORT"
};

export const BASE_URL = `http://localhost:5000/graphql`;

export const MAPBOX_API_TOKEN =
  "pk.eyJ1Ijoia2lldG5hMTI4MTAiLCJhIjoiY2thcGR6eGVqMDkwbTJ4bDU2cWNncTR5MyJ9.zH9N1pX6abNrOvZAKk3trA";
